### ISSUE TITLE
Create plan - Add name to db

### ISSUE THREAD

**Issue by paulamoller** [autyzm-pg/friendly-plans#238]
- Save plan name to db
- Add perform this action to button save
- tests

**Comment by SuperJarek** [comment]
To which entity should plan name be added? 
ChildPlan?

**Comment by malsolec** [comment]
@SuperJarek the issue is about creating plan template ( the basic screen from mock https://app.moqups.com/mikolevy2/tGR3mQdS/view/page/a5d5f2d6a, issue assumes that the screen  is already prepared in #237) - it is the description of plan and it should be stored in plan_template. This plan can be assigned to child ( even couple of times ) and then it is defined by child_plan. (https://github.com/autyzm-pg/friendly-plans/wiki/Database)

**Comment by malsolec** [comment]
Done.
