### ISSUE TITLE
Add new UI model

### ISSUE THREAD

**Issue by autyzm-pg** [autyzm-pg/friendly-plans#47]
# **ENG**:
### **Actual**:

The only UI model is outdated (has been done for prototype of first app version).
### **Expected**:

UI model of next app version.
# **PL:**
### **Stan obecny:**

Model UI jest nieaktualny (dotyczy prototypu pierwszej wersji aplikacji).
### **Stan oczekiwany:**.

Należy przygotować model UI nowej wersji aplikacji.

**Comment by vjs3** [comment]
@autyzm-pg I would love to work on this, but the app is only showing smiley face on installing from play store. Can you tell me how can I test it so that I can send a PR as part of Hacktoberfest?

**Comment by malsolec** [comment]
@vjs3 To use application please install app from store: https://play.google.com/store/apps/details?id=com.przyjaznydamianek&hl=pl and the manager for the app is https://play.google.com/store/apps/details?id=com.przyjaznydamianekDisplayer.mymodule.appmanager&hl=pl . Manager is for creating plans/schedules which the kids use with the base app. There is an user guide: http://autyzm.eti.pg.gda.pl/przyjaznyplan/instrukcja/

We are planing to rebuild app to increase its usability. Every help is welcome.
This is my proposal: https://classic.moqups.com/#!/edit/mal.solecka@gmail.com/ZTH8139I
Unfortunately you may need a dictionary or translator, because app is still in Polish, however your mockup can be in English anyway.

This is how it is being used in real https://www.youtube.com/watch?v=zI0ma_XnmCc .
