### ISSUE TITLE
POC - Merge Plan Runner and Manager into one app

### ISSUE THREAD

**Issue by DragoonAethis** [autyzm-pg/friendly-plans#53]
The primary problem people have is the "smiley face" - basically everyone expects to have some sort of a tutorial on the first start in the main app, and the plan runner doesn't do anything if no plans are found.

So, the solution would be to merge the manager and runner into a single app. Any app can provide two launcher icons, each running its own activity, per: https://stackoverflow.com/questions/3270409/how-do-i-get-multiple-icons-to-launch-different-activities-in-one-application - this would also simplify some logic currently duplicated in both apps and not extracted into the shared Core. This, along with a helpful "No plans were found, configure them first in the Manager" dialog, would suggest there's something that needs to be done first in order to use the app.

**Comment by mikolevy** [comment]
Yes, that is the problem. We wanted add tutorial to main app but it is not so simple. Friendly Plan is currently used by lot of people and version available in Google Play doesn't have serious bugs. Unfortunately we don't have tag of this version on the repo or event source code from that particular  moment. It's because app has been previously developed by students during the project at the university and after that there were same changes made in the source code and finally we received that changed version. That version already contains some serious bugs (app crashed and so on). We fixed most of them but there are still some problems. 
The most important thing is that during the "unbugging" process we conclude that current code is almost impossible to further development for us and finally it has to be rewritten. First we thought about making it module by module but we tried it and it is impossible to keep the app in good condition during that process (as I sad, even current version contains some serious bugs). So we have decided to write second version of app from scratch. Currently we're starting projecting phase. On Thursday we met therapist from IWRD and talk about requirements and new manager app design (which is available here: https://classic.moqups.com/mikolevy/rvDDG1J9 ). Their attitude was enthusiastic :) 
It's really great that you have made these issues and start repairing this code :) but I propose start with 2.0 app version work. I think we should move your concept issues to version 2.0. Maybe you'd like to start projecting 2.0 app architecture? We will push some requirements info from therapists as soon as we can (hopefully this week).
And finally about problem with the "smiley face" - your idea is great - and we should implement it like this in 2.0 version 👍

**Comment by DragoonAethis** [comment]
I'm actually a student myself, so if you'd have some time to meet, maybe this week, we could discuss that easily. (I've already sketched out some random UI ideas to clean up what's there.)

The Google Play version could at least get a disclaimer in the app description, that can be changed without submitting a new app version.

**Comment by malsolec** [comment]
Great!  Could you share them in this issue: https://github.com/autyzm-pg/friendly-plans/issues/47  Everybody would have more time to think about them. 
We are planning the meeting on next Thursday afternoon. Is KDP MeetUp meeting ok with you? I will let you know then.

**Comment by DragoonAethis** [comment]
I can't find the scheduled event anywhere on KDP sites for 3city, any links?

**Comment by mikolevy** [comment]
We confirmed room reservation and now we have meetup :)
https://www.meetup.com/Koduj-dla-Polski-Trojmiasto/events/235761098/

**Comment by DragoonAethis** [comment]
Alright, I'll be there.

**Comment by mikolevy** [comment]
Summarizing - there is need to do:
- research about using two icons in one android app
- based on it prepare POC (short info/description/explanation, code example) how build one app contained basic version and manager features (e.g. what will happen when after leaving but not turning off manager part of app user will choose the basic version of app)

**Comment by malsolec** [comment]
Resolved.
