### ISSUE TITLE
Consider using "Allow squash merging" as a default PR merge strategy

### ISSUE THREAD

**Issue by wingsofovnia** [autyzm-pg/friendly-plans#85]
"Why would I use a squash merge?
Simply put, a squash merge produces a cleaner history.  When working with topic branches, and especially when responding to code review feedback, a small change can easily grow to span multiple commits.  Interactive rebasing and force pushing is often the way to clean up these intermediate commits, but even then a new merge commit is created if you’re using pull requests and merging on the server." [1]

From my side, I believe this strategy makes master's commit history way cleaner, excludes useless "merge commits" or small changes like "fix broken test" etc. Just compare: [autyzm-pg commits](https://github.com/autyzm-pg/mroza/commits/master) and [vega dev commits](https://github.com/socialedge/vega/commits/develop).

[1] https://blogs.msdn.microsoft.com/visualstudioalm/2016/03/15/squash-a-whole-new-way-to-merge-pull-requests/

**Comment by malsolec** [comment]
We use this option from the time it was introduced by github.

**Comment by wingsofovnia** [comment]
@malsolec so why do commits like "Merge branch 'master' of https://github.com/autyzm-pg/mroza into develop" still appear in commit log?

**Comment by mikolevy** [comment]
As @malsolec sad we use this option from the time it appeared (since we had noticed it, if we want to be more precise). There is even a point about it in docs:
"Commits should be squashed if it is possible, or they will be squashed with merging(github option)."

So yes - squash merging currently is our main PR merging strategy but I'd like to point out that we allow using other strategies and it's not so big deal if somebody will use different merging style in the future.
